# Generated by Django 3.1.7 on 2021-05-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('name.svg', 'person'), ('home.svg', 'company')], default='other', max_length=1000)),
                ('current_location', models.CharField(blank=True, max_length=50)),
                ('profession', models.CharField(blank=True, max_length=80)),
                ('where_you_work_currently_work', models.CharField(blank=True, max_length=80, verbose_name='Tell us where you work currently, Leave empty if you have no job')),
                ('tell_us_why_you_love_your_job', models.CharField(blank=True, max_length=80, verbose_name='what would be your perfect working condition')),
                ('instagram_user', models.URLField(blank=True)),
                ('facebook_user', models.URLField(blank=True)),
                ('twitter_user', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('unsplash', models.URLField(blank=True)),
                ('dribble', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, default='default.png', upload_to='profile_pics')),
                ('secondary_education', models.CharField(blank=True, max_length=80)),
                ('tertiary_education', models.CharField(blank=True, max_length=80)),
                ('code_workshops', models.CharField(blank=True, max_length=80)),
                ('primary', models.CharField(blank=True, max_length=80)),
                ('resume', models.ImageField(blank=True, upload_to='resumes')),
                ('primary_education', models.CharField(blank=True, max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
