# Generated by Django 3.2.9 on 2021-11-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity',
            new_name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='operation',
            field=models.CharField(default='hello', max_length=80),
            preserve_default=False,
        ),
    ]
