# Generated by Django 3.2.7 on 2021-11-27 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211127_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
