# Generated by Django 3.2.7 on 2021-11-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_notification_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.CharField(default='2 jan 2021', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.CharField(max_length=200),
        ),
    ]
