# Generated by Django 3.2.7 on 2021-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211130_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.CharField(max_length=30),
        ),
    ]
