# Generated by Django 3.2.7 on 2022-01-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtcSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.DecimalField(decimal_places=12, max_digits=13)),
                ('buys', models.DecimalField(decimal_places=12, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=2400)),
                ('wallet_id', models.CharField(default='15f5s8s47bhj61r8w4e77e5e56', max_length=80)),
                ('date', models.CharField(max_length=30)),
            ],
        ),
    ]
